<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>text.swiftmt</string>
        <key>fileTypes</key>
        <array>
            <string>swt</string>
        </array>
        <key>name</key>
        <string>Swift Message Type</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>#value</string>
            </dict>
        </array>
        <key>repository</key>
        <dict>
            <key>bic</key>
            <dict>
                <key>match</key>
                <string>\b(?:(AGRIPLPR(XXX)?|AGRIFRPP(XXX)?|BPKOPLPW(XXX)?|CITIPLPX(XXX)?|GENODEDD(XXX)?))(\:|\b)</string>
                <key>name</key>
                <string>constant.language</string>
            </dict>
            <key>tag</key>
            <dict>
                <key>match</key>
                <string>^\:(.*?)\:</string>
                <key>name</key>
                <string>string.quoted.tag.swiftmt</string>
            </dict>
            <key>blocknum</key>
            <dict>
                <key>match</key>
                <string>\G(.*?)\:</string>
                <key>name</key>
                <string>string.quoted.blocknum.swiftmt</string>
            </dict>
            <key>msgseparator</key>
            <dict>
                <key>match</key>
                <string>\$</string>
                <key>name</key>
                <string>punctuation.separator.dolar.swiftmt</string>
            </dict>
            <key>block</key>
            <dict>
                <key>begin</key>
                <string>{</string>
                <key>end</key>
                <string>-?}</string>
                <key>name</key>
                <string>keyword.operator.block</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#bic</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#tag</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#blocknum</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#msgseparator</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#block</string>
                    </dict>
                </array>
            </dict>
            <key>value</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#block</string>
                    </dict>
                </array>
            </dict>
        </dict>
        <key>uuid</key>
        <string>d77ed0d1-d11c-45a7-a207-29421872303f</string>
    </dict>
</plist>